-- ============================================================================
-- AUTOMAÇÕES (RESPOSTAS AUTOMÁTICAS DE INSTAGRAM E MESSENGER) - TABELAS NOVAS
-- ============================================================================
-- Onde colar: entre no seu projeto em supabase.com, vá no menu "SQL Editor"
-- (ícone de terminal na lateral esquerda), clique em "New query", cole este
-- arquivo inteiro e clique em "Run".
--
-- Este arquivo é seguro de rodar mais de uma vez: ele só CRIA tabelas que
-- ainda não existem ("if not exists"). Nada aqui apaga tabela, coluna ou
-- linha nenhuma do que você já tem.
-- ============================================================================


-- ============================================================================
-- TABELA: automacoes_config
-- Só existe UMA linha nessa tabela (o "id" é sempre 1). É onde ficam
-- guardados os dados da sua ligação com o Meta (Facebook/Instagram): o Token
-- de acesso da Página, o App Secret e o Verify Token que você vai gerar no
-- Meta for Developers, além dos IDs da sua Página e da sua conta do
-- Instagram. Você preenche isso pela própria aba Automações do painel — não
-- precisa mexer em nada aqui no Supabase.
--
-- Por que existem DOIS pares de "app secret" e "token": o Meta separou o
-- Instagram num app próprio ("API do Instagram"), com ID, Chave Secreta e
-- token de acesso diferentes dos que você usa pro Messenger. Por isso os
-- campos "instagram_app_secret" e "instagram_token_acesso" guardam os dados
-- desse app separado, enquanto "app_secret" e "token_acesso_pagina" continuam
-- sendo os do app principal (usados pelo Messenger).
-- ============================================================================
create table if not exists public.automacoes_config (
  id smallint primary key default 1 check (id = 1),
  pagina_id text,
  instagram_conta_id text,
  token_acesso_pagina text,
  app_secret text,
  instagram_app_secret text,
  instagram_token_acesso text,
  verify_token text,
  atualizado_em timestamptz not null default now()
);

-- Caso você já tenha rodado uma versão anterior deste arquivo (sem essas duas
-- colunas do Instagram), estas linhas acrescentam elas sem apagar nada.
alter table public.automacoes_config add column if not exists instagram_app_secret text;
alter table public.automacoes_config add column if not exists instagram_token_acesso text;


-- ============================================================================
-- TABELA: automacoes_regras
-- Cada linha é uma automação que você criou na aba Automações: em que canal
-- ela vale (instagram ou messenger), que tipo de automação é (boas-vindas
-- pra primeira mensagem de alguém nôvo, palavra-chave pra responder quando o
-- texto recebido contém certas palavras, ou ausência pra quando nenhuma
-- outra regra se encaixou) e qual o texto de resposta.
-- ============================================================================
create table if not exists public.automacoes_regras (
  id bigint generated by default as identity primary key,
  canal text not null check (canal in ('instagram', 'messenger')),
  tipo text not null check (tipo in ('boas_vindas', 'palavra_chave', 'ausencia')),
  gatilho text,             -- palavras-chave separadas por vírgula (só usado quando tipo = 'palavra_chave')
  resposta text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: automacoes_mensagens
-- Uma linha por mensagem recebida no Instagram ou Messenger que passou pelo
-- webhook. Registra se alguma automação respondeu (e qual) ou se nenhuma
-- regra se encaixou. Sem isso, não teria como você ver o histórico do que
-- foi respondido automaticamente.
-- ============================================================================
create table if not exists public.automacoes_mensagens (
  id bigint generated by default as identity primary key,
  canal text not null,
  remetente_id text not null,      -- id de quem mandou a mensagem (Instagram ou Messenger)
  texto_recebido text,
  regra_id bigint references public.automacoes_regras(id) on delete set null,
  resposta_enviada text,
  status text not null check (status in ('ok', 'erro', 'sem_regra')),
  erro text,
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TRAVA DE SEGURANÇA (RLS)
-- Igual as suas outras tabelas: só você, logada, lê e escreve. A função que
-- recebe as mensagens do Meta (meta-webhook) não passa por essa trava porque
-- usa a chave de serviço do Supabase por trás dos panos — só ela e você têm
-- acesso a essas tabelas.
-- ============================================================================
alter table public.automacoes_config enable row level security;
alter table public.automacoes_regras enable row level security;
alter table public.automacoes_mensagens enable row level security;

drop policy if exists "automacoes_config_select_somente_logada" on public.automacoes_config;
create policy "automacoes_config_select_somente_logada"
  on public.automacoes_config for select
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_config_insert_somente_logada" on public.automacoes_config;
create policy "automacoes_config_insert_somente_logada"
  on public.automacoes_config for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_config_update_somente_logada" on public.automacoes_config;
create policy "automacoes_config_update_somente_logada"
  on public.automacoes_config for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_regras_select_somente_logada" on public.automacoes_regras;
create policy "automacoes_regras_select_somente_logada"
  on public.automacoes_regras for select
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_regras_insert_somente_logada" on public.automacoes_regras;
create policy "automacoes_regras_insert_somente_logada"
  on public.automacoes_regras for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_regras_update_somente_logada" on public.automacoes_regras;
create policy "automacoes_regras_update_somente_logada"
  on public.automacoes_regras for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_regras_delete_somente_logada" on public.automacoes_regras;
create policy "automacoes_regras_delete_somente_logada"
  on public.automacoes_regras for delete
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_mensagens_select_somente_logada" on public.automacoes_mensagens;
create policy "automacoes_mensagens_select_somente_logada"
  on public.automacoes_mensagens for select
  using ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_mensagens_insert_somente_logada" on public.automacoes_mensagens;
create policy "automacoes_mensagens_insert_somente_logada"
  on public.automacoes_mensagens for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "automacoes_mensagens_delete_somente_logada" on public.automacoes_mensagens;
create policy "automacoes_mensagens_delete_somente_logada"
  on public.automacoes_mensagens for delete
  using ( auth.role() = 'authenticated' );


-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
