-- ============================================================================
-- BANCO DE DADOS DO PAINEL DA LUANA COIN
-- ============================================================================
-- Onde colar: entre no seu projeto em supabase.com, vá no menu "SQL Editor"
-- (ícone de terminal na lateral esquerda), clique em "New query", cole este
-- arquivo inteiro e clique em "Run". Pode rodar tudo de uma vez, de cima a
-- baixo, numa tacada só.
--
-- Se precisar rodar de novo do zero, cada tabela é criada com "if not exists"
-- para não dar erro caso já exista.
-- ============================================================================


-- ============================================================================
-- TABELA: videos
-- Os vídeos de destaque e do portfólio que aparecem no seu site.
-- ============================================================================
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  link text not null,
  nicho text not null,
  formato text not null,
  marca text,
  destaque text,              -- texto livre, ex: "2,4M views" ou "980 mil views"
  ordem integer not null default 0,   -- ordem de exibição no site (menor aparece primeiro)
  visivel boolean not null default true,  -- se falso, some do site mas continua no admin
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: marcas
-- Sua base de contatos de empresas (leads, clientes, etc).
-- ============================================================================
create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nome text not null,
  instagram text,
  email text,
  telefone text,
  situacao text not null default 'lead'
    check (situacao in ('lead', 'conversando', 'cliente', 'parada')),
  obs text,
  ultimo_contato date,
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: calendario
-- Sua agenda de gravar, editar e postar.
-- ============================================================================
create table if not exists public.calendario (
  id bigint generated by default as identity primary key,
  titulo text not null,
  marca text,
  tipo text not null
    check (tipo in ('gravar', 'editar', 'postar')),
  data date not null,
  status text not null default 'a_fazer'
    check (status in ('a_fazer', 'feito')),
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: campanhas
-- As campanhas fechadas com marcas, com valores e prazos.
-- ============================================================================
create table if not exists public.campanhas (
  id bigint generated by default as identity primary key,
  campanha text not null,
  cliente text not null,
  tipo text not null
    check (tipo in ('Conteúdo', 'Publicidade')),
  status text not null default 'Briefing'
    check (status in ('Briefing', 'Roteiro', 'Aprovação Roteiro', 'Gravação', 'Edição', 'Aprovado', 'Entregue')),
  qtd integer not null default 1,
  valor numeric(10,2) not null default 0,
  prazo date,
  pagamento text not null default 'pendente'
    check (pagamento in ('pendente', 'pago')),
  ativa boolean not null default true,
  favorita boolean not null default false,
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: marcados
-- Guarda o que você já marcou no checklist do portfólio (aba Checklist do
-- admin). Cada item do checklist tem uma "chave" de texto única.
-- ============================================================================
create table if not exists public.marcados (
  chave text primary key,
  marcado boolean not null default true,
  atualizado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: visitas
-- Um registro simples de cada vez que alguém abre uma página do seu site.
-- Usado só para as métricas do admin (visitas por dia, de onde vieram).
-- ============================================================================
create table if not exists public.visitas (
  id bigint generated by default as identity primary key,
  data timestamptz not null default now(),
  pagina text,
  origem text
);


-- ============================================================================
-- TRAVA DE SEGURANÇA (RLS = Row Level Security)
-- ============================================================================
-- A partir daqui, ligamos a trava em TODAS as tabelas. Com a trava ligada,
-- por padrão NINGUÉM consegue ler ou escrever nada, exceto o que for
-- explicitamente liberado pelas regras (as "policies") abaixo.
--
-- Regra geral em todas as tabelas: só você, logada, pode ler e escrever.
--
-- Exceções (só estas três, explicadas uma por uma):
--   1) marcas: qualquer pessoa pode INSERIR (é o formulário de contato do site)
--   2) visitas: qualquer pessoa pode INSERIR (é o registro de visita do site)
--   3) videos: qualquer pessoa pode LER os vídeos marcados como visíveis
--      (sem isso, seu portfólio publicado não consegue mostrar nenhum vídeo
--      para quem visita, porque quem visita não está logada). Nenhum dado
--      sensível fica nessa tabela, então essa exceção é segura.
-- ============================================================================

alter table public.videos enable row level security;
alter table public.marcas enable row level security;
alter table public.calendario enable row level security;
alter table public.campanhas enable row level security;
alter table public.marcados enable row level security;
alter table public.visitas enable row level security;


-- ---------- videos ----------
-- Qualquer pessoa pode ler os vídeos visíveis (para o site funcionar).
-- Você, logada, pode ler todos (visíveis ou não, para editar no admin).
create policy "videos_select_publico_ou_logada"
  on public.videos for select
  using ( visivel = true or auth.role() = 'authenticated' );

-- Só você, logada, pode adicionar, editar ou apagar vídeos.
create policy "videos_insert_somente_logada"
  on public.videos for insert
  with check ( auth.role() = 'authenticated' );

create policy "videos_update_somente_logada"
  on public.videos for update
  using ( auth.role() = 'authenticated' );

create policy "videos_delete_somente_logada"
  on public.videos for delete
  using ( auth.role() = 'authenticated' );


-- ---------- marcas ----------
-- Só você, logada, pode ler a sua base de contatos.
create policy "marcas_select_somente_logada"
  on public.marcas for select
  using ( auth.role() = 'authenticated' );

-- Qualquer pessoa pode inserir (é o formulário de contato do portfólio).
create policy "marcas_insert_qualquer_pessoa"
  on public.marcas for insert
  with check ( true );

-- Só você, logada, pode editar ou apagar.
create policy "marcas_update_somente_logada"
  on public.marcas for update
  using ( auth.role() = 'authenticated' );

create policy "marcas_delete_somente_logada"
  on public.marcas for delete
  using ( auth.role() = 'authenticated' );


-- ---------- calendario ----------
-- Só você, logada, pode ler, adicionar, editar ou apagar.
create policy "calendario_select_somente_logada"
  on public.calendario for select
  using ( auth.role() = 'authenticated' );

create policy "calendario_insert_somente_logada"
  on public.calendario for insert
  with check ( auth.role() = 'authenticated' );

create policy "calendario_update_somente_logada"
  on public.calendario for update
  using ( auth.role() = 'authenticated' );

create policy "calendario_delete_somente_logada"
  on public.calendario for delete
  using ( auth.role() = 'authenticated' );


-- ---------- campanhas ----------
-- Só você, logada, pode ler, adicionar, editar ou apagar.
create policy "campanhas_select_somente_logada"
  on public.campanhas for select
  using ( auth.role() = 'authenticated' );

create policy "campanhas_insert_somente_logada"
  on public.campanhas for insert
  with check ( auth.role() = 'authenticated' );

create policy "campanhas_update_somente_logada"
  on public.campanhas for update
  using ( auth.role() = 'authenticated' );

create policy "campanhas_delete_somente_logada"
  on public.campanhas for delete
  using ( auth.role() = 'authenticated' );


-- ---------- marcados ----------
-- Só você, logada, pode ler, marcar ou desmarcar itens do checklist.
create policy "marcados_select_somente_logada"
  on public.marcados for select
  using ( auth.role() = 'authenticated' );

create policy "marcados_insert_somente_logada"
  on public.marcados for insert
  with check ( auth.role() = 'authenticated' );

create policy "marcados_update_somente_logada"
  on public.marcados for update
  using ( auth.role() = 'authenticated' );

create policy "marcados_delete_somente_logada"
  on public.marcados for delete
  using ( auth.role() = 'authenticated' );


-- ---------- visitas ----------
-- Qualquer pessoa pode inserir (é o registro de visita do portfólio).
create policy "visitas_insert_qualquer_pessoa"
  on public.visitas for insert
  with check ( true );

-- Só você, logada, pode ler ou apagar os registros de visita.
create policy "visitas_select_somente_logada"
  on public.visitas for select
  using ( auth.role() = 'authenticated' );

create policy "visitas_delete_somente_logada"
  on public.visitas for delete
  using ( auth.role() = 'authenticated' );


-- ============================================================================
-- LINHAS DE EXEMPLO
-- ============================================================================
-- Uma linha em cada tabela principal, só para você ver o formato dos dados
-- no admin. Todas estão bem marcadas como exemplo. Pode editar ou apagar
-- direto pelo painel quando quiser, a hora que quiser.
--
-- Os vídeos de exemplo entram como "visivel = false", ou seja, NÃO aparecem
-- no seu site publicado, só no admin, até você criar e marcar os seus de
-- verdade como visíveis.
-- ============================================================================

insert into public.videos (titulo, link, nicho, formato, marca, destaque, ordem, visivel)
values (
  '(Exemplo, apague depois de entender o formato)',
  'https://exemplo.com/meu-video',
  'Beleza',
  'vídeo vertical 9:16',
  'Marca Exemplo',
  'Exemplo: 2,4M views',
  1,
  false
);

insert into public.marcas (nome, instagram, email, telefone, situacao, obs, ultimo_contato)
values (
  '(Exemplo, apague depois) Empresa Exemplo',
  '@empresaexemplo',
  'contato@exemplo.com',
  '11999990000',
  'lead',
  'Isso é só um exemplo de como fica uma linha preenchida. Pode apagar.',
  current_date
);

insert into public.calendario (titulo, marca, tipo, data, status)
values (
  '(Exemplo, apague depois) Gravar vídeo de unboxing',
  'Marca Exemplo',
  'gravar',
  current_date,
  'a_fazer'
);

insert into public.campanhas (campanha, cliente, tipo, status, qtd, valor, prazo, pagamento, ativa, favorita)
values (
  '(Exemplo, apague depois) Campanha Exemplo',
  'Cliente Exemplo',
  'Conteúdo',
  'Briefing',
  1,
  0,
  current_date + interval '7 days',
  'pendente',
  true,
  false
);


-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
