-- ============================================================================
-- DISPARO DE E-MAILS - TABELAS E COLUNAS NOVAS
-- ============================================================================
-- Onde colar: entre no seu projeto em supabase.com, vá no menu "SQL Editor"
-- (ícone de terminal na lateral esquerda), clique em "New query", cole este
-- arquivo inteiro e clique em "Run".
--
-- Este arquivo é seguro de rodar mais de uma vez: ele só CRIA tabelas que
-- ainda não existem ("if not exists") e ACRESCENTA colunas nas tabelas que
-- já existem ("add column if not exists"). Nada aqui apaga tabela, coluna
-- ou linha nenhuma do que você já tem.
-- ============================================================================


-- ============================================================================
-- DUAS COLUNAS NOVAS NA TABELA "marcas" (a sua base de sempre)
-- ============================================================================

-- "selecionada": pra você marcar, na aba Marcas, quais marcas quer escolher
-- pra um disparo de e-mail. Fica salva no banco, então a seleção não se
-- perde quando você fecha o admin e volta outro dia.
alter table public.marcas add column if not exists selecionada boolean not null default false;

-- "ultimo_envio_email": a data em que essa marca recebeu o último e-mail de
-- um disparo feito pela aba Disparo de E-mails.
alter table public.marcas add column if not exists ultimo_envio_email date;


-- ============================================================================
-- TABELA: email_envios
-- Uma linha por marca, por e-mail que sai. É o registro de tudo que foi
-- enviado (ou tentado enviar). Sem isso, se um disparo parar no meio do
-- caminho, não tem como saber quem recebeu e quem não recebeu.
-- ============================================================================
create table if not exists public.email_envios (
  id bigint generated by default as identity primary key,
  email text not null,
  assunto text not null,
  status text not null check (status in ('ok', 'erro')),
  erro text,               -- mensagem de erro do Resend, quando status = 'erro'
  resend_id text,          -- id que o Resend devolve pra cada e-mail enviado
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TABELA: email_optout
-- E-mails que pediram pra não receber mais (responderam SAIR). Uma vez aqui,
-- nunca mais entram em nenhum disparo, em nenhum assunto.
-- ============================================================================
create table if not exists public.email_optout (
  email text primary key,
  criado_em timestamptz not null default now()
);


-- ============================================================================
-- TRAVA DE SEGURANÇA (RLS)
-- Igual as suas outras tabelas: só você, logada, lê e escreve. Ninguém
-- deslogado enxerga nada em nenhuma das duas.
-- ============================================================================
alter table public.email_envios enable row level security;
alter table public.email_optout enable row level security;

drop policy if exists "email_envios_select_somente_logada" on public.email_envios;
create policy "email_envios_select_somente_logada"
  on public.email_envios for select
  using ( auth.role() = 'authenticated' );

drop policy if exists "email_envios_insert_somente_logada" on public.email_envios;
create policy "email_envios_insert_somente_logada"
  on public.email_envios for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "email_envios_delete_somente_logada" on public.email_envios;
create policy "email_envios_delete_somente_logada"
  on public.email_envios for delete
  using ( auth.role() = 'authenticated' );

drop policy if exists "email_optout_select_somente_logada" on public.email_optout;
create policy "email_optout_select_somente_logada"
  on public.email_optout for select
  using ( auth.role() = 'authenticated' );

drop policy if exists "email_optout_insert_somente_logada" on public.email_optout;
create policy "email_optout_insert_somente_logada"
  on public.email_optout for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "email_optout_delete_somente_logada" on public.email_optout;
create policy "email_optout_delete_somente_logada"
  on public.email_optout for delete
  using ( auth.role() = 'authenticated' );


-- ============================================================================
-- FIM DO SCRIPT
-- ============================================================================
